version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ${POSTGRES_HOST}
    ports:
      - '5432:5432'
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: job_board_pgadmin
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

  api:
    container_name: job_board_backend
    build:
      context: .
      dockerfile: api/Dockerfile
    command: ./start.sh
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  web:
    cpus: 2
    container_name: job_board_frontend
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - '4200:4200'
    depends_on:
      - api
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

volumes:
  pgdata:
  
networks:
  app-network:
    driver: bridge
